BasicSettings/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.conf.urls import url
from BasicSettings.views  import  *


    

#(?P<slug>[\w-]+)/$
app_name = 'basic'
urlpatterns = [
    
    path('uom', UomSetup , name='uom'),
    path('addUomDetailsFormRow' ,addUomDetailsFormRow  ,  name='addUomDetailsFormRow'),
    path('SaveUom' ,SaveUom  ,  name='SaveUom'),
    path('EditUom' ,EditUom  ,  name='EditUom'),
    path('UpdateUom' ,UpdateUom,name='UpdateUom' ),
    path('uomInfo/<int:uom>/' ,EditUom  ,  name='uomInfo'),
    path('UomList' ,UomListView.as_view(),name='UomList' ),
    path('GetUomDetailsByMaster' ,GetUomDetailsByMaster,name='GetUomDetailsByMaster' ),

    #region ItemGroup

    path('newgroup', NewGroup , name='NewGroup'),
    path('SaveGroup', SaveGroup , name='SaveGroup'),
    path('groups', GroupList.as_view() , name='groups'),
    path('EditGroup/<int:group>/', EditGroup , name='EditGroup'),
    path('UpdateGroup', UpdateGroup , name='UpdateGroup'),

    #end region

    #region Item Category
    path('newcategory', NewCategory , name='newcategory'),
    path('SaveCategory', SaveCategory , name='SaveCategory'),
    path('UpdateCategory', UpdateCategory , name='UpdateCategory'),
    
    path('category/<int:cat>/', EditCategory , name='category'),
    path('categories', CategoryListView.as_view() , name='categories'),
    #endregion

    #region Item Brand
    path('newbrand', NewBrand , name='newbrand'),
    path('SaveBrand', SaveBrand , name='SaveBrand'),
    path('brands', BrandListView.as_view() , name='brands'),
    path('brand/<int:brand>/', EditBrand , name='brand'),
    path('UpdateBrand', UpdateBrand , name='UpdateBrand'),

    #endregion

    #regiom Item Color
    path('newcolor', NewColor , name='newcolor'),
    path('SaveColor', SaveColor , name='SaveColor'),
    path('colors', ColorListView.as_view() , name='colors'),
    path('colorE/<int:color>/', EditColor , name='colorE'),
    path('UodateColor', UodateColor , name='UodateColor'),


    #endregion

    #regiom Item Size
    path('newsize', NewSize , name='newsize'),
    path('SaveSize', SaveSize , name='SaveSize'),
    path('sizes', SizeListView.as_view() , name='sizes'),
    path('size/<int:size>/', EditSize , name='size'),
    path('UodateSize', UodateSize , name='UodateSize'),


    #endregion
    
    

    
 

    







]
urlpatterns+=[


]

Inventory/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from Home.views import Index
# from BasicSettings.views  import  homeView , UOMSetup, ajaxTest

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', homeView),
    #path('uom', UOMSetup),
    # path('ajaxTest', ajaxTest,name='ajaxTest'),
    path('',Index , name="index"),
    path('basic/', include('BasicSettings.urls',namespace='basic')),
    path('prod/', include('ProductSetup.urls')),
    path('prod/', include('ProductSetup.urls')),


]

BasicSettings/models.py
from django.db import models

class ItemGroupManager(models.Manager):
    def GetItemGroup(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None

class ItemGroup(models.Model):
    ItemGroupName = models.CharField(max_length=120)
    GroupShortName = models.CharField(max_length=5  )
    IsActive = models.BooleanField(default=True)
    IsDelete = models.BooleanField(default=False)
    CreateBy = models.CharField(max_length=500  )
    CreateDate = models.DateTimeField(auto_now_add=True )
    UpdateBy = models.CharField(max_length=500 , blank=True,null=True )
    UpdateDate = models.DateTimeField(auto_now=True,blank=True,null=True )
    DeleteBy = models.CharField(max_length=500 , blank=True,null=True )
    objects = ItemGroupManager()

    def __str__(self):

        return  self.ItemGroupName+':'+self.GroupShortName




    
#endregion

#region ItemCategory
class ItemCategoryManager(models.Manager):
    def GetItemCategory(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None
class ItemCategory(models.Model):
    ItemGroup = models.ForeignKey(ItemGroup, on_delete=models.CASCADE)
    ItemCategory = models.CharField(max_length=120)
    CategoryShortName = models.CharField(max_length=5  )
    IsDelete = models.BooleanField(default=False)
    CreateBy = models.CharField(max_length=500  )
    CreateDate = models.DateTimeField(auto_now_add=True  )
    UpdateBy = models.CharField(max_length=500 , blank=True,null=True )
    UpdateDate = models.DateTimeField(auto_now=True,blank=True,null=True )
    DeleteBy = models.CharField(max_length=500 , blank=True,null=True )
    IsActive = models.BooleanField(default=True)
    objects = ItemCategoryManager()


    def __str__(self):

        return  self.ItemCategory+':'+self.CategoryShortName
#endregion

class UomMasterManager(models.Manager):
    def GetUomMasterId(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None
class UomMaster(models.Model):
    UomMasterName =  models.CharField(max_length=500)
    UomMasterShortName =  models.CharField(max_length=500)
    IsActive = models.BooleanField(default=True)
    IsDelete = models.BooleanField(default=False)
    CreateBy = models.CharField(max_length=500 , blank=True)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    UpdateBy = models.CharField(max_length=500 , blank=True)
    UpdateDate = models.DateTimeField(auto_now=True,blank=True)
    DeleteBy = models.CharField(max_length=500 , blank=True)
    objects = UomMasterManager()
    
    def __str__(self):

        return  self.UomMasterName
    


class UomDetailsManager(models.Manager):
    def GetUomDetailsId(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None
    
        

class UomDetails(models.Model):
    UomMaster = models.ForeignKey(UomMaster, on_delete=models.CASCADE)
    UomDetailsName = models.CharField(max_length=500,blank=False)
    UomDetailsShortName = models.CharField(max_length=500 , blank=False)
    ConversionValue = models.DecimalField(max_digits=18, decimal_places=3, default=1,blank=False)
    EqualToMaster = models.BooleanField(default=False , blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    objects = UomDetailsManager()
    
    

    def __str__(self):

        return  self.UomDetailsName+':'+self.UomDetailsShortName

class UomDetailsUpdateLog(models.Model):
    UomDetails = models.ForeignKey(UomDetails,on_delete=models.SET_NULL,null=True)
    UomMaster = models.ForeignKey(UomMaster,on_delete=models.SET_NULL,null=True)
    UomDetailsName = models.CharField(max_length=500,blank=False)
    UomDetailsShortName = models.CharField(max_length=500 , blank=False)
    ConversionValue = models.DecimalField(max_digits=18, decimal_places=3, default=1,blank=False)
    EqualToMaster = models.BooleanField(default=False , blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    CreateBy = models.CharField(max_length=500 , blank=True)



class ItemBrandManager(models.Manager):
    def GetItemBrand(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None
class ItemBrand(models.Model):
    ItemBrandName =  models.CharField(max_length=500,blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    IsDelete = models.BooleanField(default=False,blank=False)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    CreateBy = models.CharField(max_length=500 , blank=True)
    DeleteDate = models.DateTimeField( null=True ,blank=True)
    DeleteBy = models.CharField(max_length=500 , blank=True , null = True)
    UpdateBy = models.CharField(max_length=500 , blank=True)
    UpdateDate = models.DateTimeField(auto_now=True,blank=True)
    objects = ItemBrandManager()
    
    
    def __str__(self):

        return  self.ItemBrandName

class ItemColorManager(models.Manager):
    def GetItemColor(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None

class ItemColor(models.Model):
    ItemColorName =  models.CharField(max_length=500,blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    IsDelete = models.BooleanField(default=False,blank=False)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    CreateBy = models.CharField(max_length=500 , blank=True)
    DeleteDate = models.DateTimeField(  blank=True , null = True)
    DeleteBy = models.CharField(max_length=500 , blank=True , null = True)
    UpdateBy = models.CharField(max_length=500 , blank=True)
    UpdateDate = models.DateTimeField(auto_now=True,blank=True)
    objects = ItemColorManager()
      
    def __str__(self):

        return  self.ItemColorName


class ItemSizeManager(models.Manager):
    def GetItemSize(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None
class ItemSize(models.Model):
    ItemSizeName =  models.CharField(max_length=1000,blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    IsDelete = models.BooleanField(default=False,blank=False)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    CreateBy = models.CharField(max_length=500 , blank=True)
    DeleteDate = models.DateTimeField(  blank=True , null=True)
    DeleteBy = models.CharField(max_length=500 , blank=True,null=True)
    UpdateBy = models.CharField(max_length=500 , blank=True)
    UpdateDate = models.DateTimeField(auto_now=True,blank=True)
    objects = ItemSizeManager()
      
    def __str__(self):

        return  self.ItemSizeName


class CountryOriginManager(models.Manager):
    def GetItemCountry(self , pk):
        qs = self.get_queryset().filter(pk = pk)
        if qs.count()==1:
            return  qs.first
        return  None


class CountryOrigin(models.Model):
    CountryName = models.CharField(max_length=500,blank=False)
    CountryShortName = models.CharField(max_length=5,blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    IsDelete = models.BooleanField(default=False,blank=False)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    CreateBy = models.CharField(max_length=500 , blank=True)
    UpdateBy = models.CharField(max_length=500 , blank=True)
    UpdateDate = models.DateTimeField(auto_now=True,blank=True)
    DeleteDate = models.DateTimeField(  blank=True)
    DeleteBy = models.CharField(max_length=500 , blank=True)
    objects = CountryOriginManager()

    def __str__(self):
        return  self.CountryName

    

Home/models.py
from django.db import models

# Create your models here.

Home/views.py
from django.shortcuts import render
from MenuSetup.models import *
# Create your views here.

def Index(request):

    appMenu = AppMenu.objects.filter(IsActive=True,IsDelete=False)
    # context = {
    #     'menuItem' : 'Lol'
    # }
    return render(request , 'BasicSettings/homeView.html',{})

def MenuGeneration(context):
    con = context
    path = str(con.path)
    appMenu = AppMenu.GetMenuStepOne(path)
                
    asd2 = list(appMenu[0].MenuStepTwoList)
    
    return {'appMenu' : appMenu , 'path':path}

templates/BasicSettings/EditColor.html
{% extends "baseTemplates/_baseTemplate.html" %}
{% block content%}


    <div class="row"> 
        <div class="col-md-offset-2 col-md-6">
            <div class="box box-primary" >
                
               <form>{% csrf_token %}
                 <div id="fromMaster" >
                    {% include 'BasicSettings/_colorForm.html' with   masterForm=masterForm   %}
                </div>
                <input type="hidden" id="colorId" value="{{masterId}}"/>
               </form>
                <button class="btn btn-success btn-sm text-center" onclick="EditColor()" ><span class="fa fa-save"><span>&nbsp; Update Color</button>
                    
                
                
                  
            </div>
        </div>
    </div>


    <script>

    
    function EditColor(){
        debugger;
        var jsonData = {};
        jsonData["ItemColorName"] =$.trim($("#id_ItemColorName").val()); 
        
        jsonData["IsActive"] = $('#id_IsActive').is(':checked')?'True':'False';
        jsonData["id"] =$.trim($("#colorId").val()); 
        AjaxSetup();
        var urlpath = '{% url "UodateColor"   %}';
        $.ajax({
               
                data:  JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST",

                success:function (response,status, xhr) 
                {
                    debugger;
                      
                    var ct = xhr.getResponseHeader("content-type");

                    
                    if(ct=="application/json")
                    {
                    var error =  JSON.parse(response)
                    var asd = error.HasError
                    
                    if(error.HasError)
                    {
                        
                        $('#fromMaster').empty();
                        $('#fromMaster').append(error.TheData)
                    }
                    if(error["IsSuccess"]==true){
                      window.location.href  = '{% url "colors"   %}';
                    }
                }

                }
                
            });

    }


        function AjaxSetup(){
          $.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
    });
}

    </script>
{% endblock %}

templates/BasicSettings/EditGroup.html
{% extends "baseTemplates/_baseTemplate.html" %}
{% block content%}


    <div class="row"> 
        <div class="col-md-offset-2 col-md-6">
            <div class="box box-primary" >
                
               <form>{% csrf_token %}
                 <div id="fromMaster" >
                    {% include 'BasicSettings/_itemGroupForm.html' with   masterEditForm=masterEditForm   %}
                </div>
                <input type="hidden" id="groupId" value="{{masterId}}"/>
               </form>
                <button class="btn btn-success btn-sm" onclick="EditItemGroup()" ><span class="fa fa-save"><span>&nbsp; Save UOM</button>
                    
                
                
                  
            </div>
        </div>
    </div>


    <script>

    
    function EditItemGroup(){
        debugger;
        var jsonData = {};
        jsonData["ItemGroupName"] =$.trim($("#id_ItemGroupName").val()); 
        jsonData["GroupShortName"] =$.trim($("#id_GroupShortName").val()); 
        jsonData["id"] =$.trim($("#groupId").val()); 
        jsonData["IsActive"] = $('#id_IsActive').is(':checked')?'True':'False';
        AjaxSetup();
        var urlpath = '{% url "basic:UpdateGroup"   %}';
        $.ajax({
               
                data:  JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST",

                success:function (response,status, xhr) 
                {
                      
                    var ct = xhr.getResponseHeader("content-type");

                    
                    if(ct=="application/json")
                    {
                    var error =  JSON.parse(response)
                    var asd = error.HasError
                    
                    if(error.HasError)
                    {
                        
                        $('#fromMaster').empty();
                        $('#fromMaster').append(error.TheData)
                    }
                    if(error["IsSuccess"]==true){
                      window.location.href  = '{% url "basic:groups"   %}';
                    }
                }

                }
                
            });
    }


        function AjaxSetup(){
          $.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
    });
}

    </script>
{% endblock %}

templates/BasicSettings/NewColor.html
{% extends "baseTemplates/_baseTemplate.html" %}
{% block content%}


    <div class="row"> 
        <div class="col-md-offset-2 col-md-6">
            <div class="box box-primary" >
                
               <form>{% csrf_token %}
                 <div id="fromMaster" >
                    {% include 'BasicSettings/_colorForm.html' %}
                </div>
                
               </form>
                <button class="btn btn-success btn-sm" onclick="SaveColor()" ><span class="fa fa-save"><span>&nbsp; Save </button>
                    
                
                
                  
            </div>
        </div>
    </div>

    <script>

     function SaveColor(){

       debugger;
        var jsonData = {};
        jsonData["ItemColorName"] =$.trim($("#id_ItemColorName").val()); 
        
        jsonData["IsActive"] = $('#id_IsActive').is(':checked')?'True':'False';
        AjaxSetup();
        var urlpath = '{% url "SaveColor"   %}';
        $.ajax({
               
                data:  JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST",

                success:function (response,status, xhr) 
                {
                   debugger;
                      
                    var ct = xhr.getResponseHeader("content-type");

                    
                    if(ct=="application/json")
                    {
                    var error =  JSON.parse(response)
                    var asd = error.HasError
                    
                    if(error.HasError)
                    {
                        
                        $('#fromMaster').empty();
                        $('#fromMaster').append(error.TheData)
                    }
                    if(error["IsSuccess"]==true){
                      window.location.href  = '{% url "colors"   %}';
                    }
                }

                }
                
            });

    }
  


        function AjaxSetup(){
          $.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
    });
}

    </script>

{% endblock %}

templates/BasicSettings/UomSetup.html
{% extends "baseTemplates/_baseTemplate.html" %}
{% block content%}


    <div class="row"> 
        <div class="col-md-offset-2 col-md-6">
            <div class="box box-primary" >
                
               <form>
                 <div id="fromMaster" >
                    {% include 'BasicSettings/_uomMasterForm.html' %}
                </div>
               </form>
                    
                

                  
            </div>
        </div>


        <div class="col-md-offset-2 col-md-6">
            <div class="box box-primary">
                
                <form>
               
                <div id="detailsForm">
                    
                        {% include 'BasicSettings/_uomDetailsForm.html' %}
                    
                </div>
                </form>

                  <button class="btn btn-primary btn-sm" onclick="AddInList()" ><span class="fa fa-save"><span>&nbsp; Add In List</button>
            </div>
        </div>
    </div>



    <div class="row">
        <div class="col-md-offset-1 col-md-8">
            <div class="box box-primary">
                <table class="table table-bordered" id="detailsTable">
                    <thead>
                       <tr>
                            <th>
                                UOM Details
                            </th>
                           <th>
                               Short Form
                            </th>
                           <th>
                               Conversion Value
                           </th>
                           <th>
                               Equal To Master
                           </th>
                           <th>Action</th>

                       </tr>
                    </thead>
                     <tbody>
                    </tbody>
                </table>
                
                <button class="btn btn-success btn-sm" onclick="SaveUom()" ><span class="fa fa-save"><span>&nbsp; Save UOM</button>
               
            
            </div>

        </div>
        
    </div>

<script type="text/javascript">

    const detailsForm =$('#detailsForm').html(); 
    $(document).ready(function(){
      
    });
    
     function SaveUom(){
         
       debugger;
       var jsonData = {};
       jsonData["UomMasterName"] = $.trim($("#id_UomMasterName").val());
       jsonData["UomMasterShortName"] = $.trim($("#id_UomMasterShortName").val());
       jsonData["IsActive"] = $('#id_IsActive').is(':checked')?'True':'False';
       
       var jsonObj = [];
        $('#detailsTable tbody tr').each(function() { 
            
            debugger;
            var id = $.trim($(this).find('.hide').val());
            
            var detailObj = {};
            detailObj["UomMaster"] = 0;
            detailObj["UomDetailsName"] = $('#'+id+'_UomDetailsName').val();
            detailObj["UomDetailsShortName"] =  $('#'+id+'_UomDetailsShortName').val();
            detailObj["ConversionValue"] =$('#'+id+'_ConversionValue').val();
            detailObj["EqualToMaster"] = $('#'+id+'_EqualToMaster').is(':checked')?'True':'False';
            jsonObj.push(detailObj);
        }); 

        jsonData["UomDetails"] = jsonObj;

        var a = "asd";
        var aa = jsonData;
        var urlpath = '{% url "basic:SaveUom"   %}';
        $.ajax({
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST",

                success:function (response,status, xhr) 
                {
                    
                    debugger;
                      
                    var ct = xhr.getResponseHeader("content-type");

                    
                    if(ct=="application/json")
                    {
                    var error =  JSON.parse(response)
                    var asd = error.HasError
                    
                    if(error.HasError)
                    {
                        
                        $('#fromMaster').empty();
                        $('#fromMaster').append(error.TheData)
                    }
                    if(error["IsSuccess"]==true){
                      window.location.href  = '{% url "basic:UomList"   %}';
                    }
                }
                    

                }
                
            });
            

    }

    function DeleteRow(tr){
        if( $('#detailsTable tbody tr').length>1)
        {
            $('#tr_'+tr).remove();
        }
    }
     function AddInList(){
        
       var jsonData = {};
       var uomName = $.trim($("#id_UomDetailsName").val());
       var uomShortName = $.trim($('#id_UomDetailsShortName').val());
       var conversionValue = isNaN(parseFloat($.trim($('#id_ConversionValue').val())))?0:parseFloat($.trim($('#id_ConversionValue').val()));
       var count = $('#detailsTable tbody tr').length;
       var equalToMaster = $('#id_EqualToMaster').is(':checked')?'True':'False';

        jsonData["UomDetailsName"] = uomName;
        jsonData["UomDetailsShortName"] = uomShortName;
        jsonData["ConversionValue"] = conversionValue;
        jsonData["EqualToMaster"] = equalToMaster;
        jsonData["trCount"] = count;
        var urlpath = '{% url "basic:addUomDetailsFormRow"   %}';
        AjaxSetup();
        
        $.ajax({
               
                data:  JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST",
                success:function (response,status, xhr) 
                {
                         
                    var ct = xhr.getResponseHeader("content-type");                    
                    if(ct=="application/json")
                    {
                    var error =  JSON.parse(response);
                    
                    
                    if(error.HasError)
                    {
                        
                        $('#detailsForm').empty();
                        $('#detailsForm').append(error.TheData)
                    }
                    if(error["IsSuccess"]==true){
                      
                    $('#detailsTable tbody ').append(error.TheData);
                    $('#detailsForm').empty();
                    $('#detailsForm').html(detailsForm);
                    }
                }

                }
                
            });
        
             

    
    }



   
   
function AjaxSetup(){
          $.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
});


}


    function Validation(){
        var isValid = true;


        var detailsName = $.trim($("#uomDetailsName").val());
        var detailsShortName = $.trim($("#uomDetailsShortName").val());
        var conversionValue = parseFloat($("#conversionValue").val());
        var equalToMaster = $('#equalToMaster').is(':checked')?true:false;
        
        if($("#uomDetailsName").val()=='' || $("#uomDetailsName").val()==null){

            ValidationColorChange('uomDetailsName' ,'divForuomDetailsName' , "UOM Details Required ", false );
            isValid = false;
        }

         if($("#uomDetailsName").val()=='' || $("#uomDetailsName").val()==null){

            ValidationColorChange('uomDetailsName' ,'divForuomDetailsName' , "UOM Details Required ", false );
            isValid = false;
        }

        if($("#uomDetailsShortName").val()=='' || $("#uomDetailsShortName").val()==null){

            ValidationColorChange('uomDetailsShortName' ,'divForuomDetailsShortName' , "UOM Short Name Required ", false );
            isValid = false;
        }

        if($("#conversionValue").val()=='' || $("#conversionValue").val()==null ||  parseFloat($("#conversionValue").val())<=0){

            ValidationColorChange('conversionValue' ,'divForconversionValue' , "Valid Conversion Value Required ", false );
            isValid = false;
        }

        $('#detailsTable tbody tr').each(function() { 

           

            if( $.trim($(this).find('.name').html()) ==  $.trim($("#uomDetailsName").val())){
                
                ValidationColorChange('uomDetailsName' ,'divForuomDetailsName' , "UOM Details Already Exists ", false );
                return flase;
            }

            if( $.trim($(this).find('.shortName').html()) == $.trim($("#uomDetailsShortName").val())){
                
                ValidationColorChange('uomDetailsShortName' ,'divForuomDetailsShortName' , "UOM Short Name Already Exists ", false );
                return flase;
            }
           

        });


        
        return isValid;
    }
</script>
{% endblock %}

templates/BasicSettings/_brandForm.html
<div class="row" id="divForItemBrandName">
    <label>Brand Name:</label>
    {{masterForm.ItemBrandName}}
    <label class="text-danger" >{{masterForm.errors.ItemBrandName.as_text }}</label>
      
</div>


<div class="row" id="divForIsActive">
    <label>Is Active:</label>
    {{masterForm.IsActive}}
    {% comment %} <label class="text-danger" >{{masterForm.errors.IsActive.as_text }}</label> {% endcomment %}
      
</div>