Inventory/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from Home.views import Index
# from BasicSettings.views  import  homeView , UOMSetup, ajaxTest

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', homeView),
    #path('uom', UOMSetup),
    # path('ajaxTest', ajaxTest,name='ajaxTest'),
    path('',Index , name="index"),
    path('basic/', include('BasicSettings.urls',namespace='basic')),
    path('prod/', include('ProductSetup.urls')),
    path('prod/', include('ProductSetup.urls')),


]

ProductSetup/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.conf.urls import url
from ProductSetup.views  import  (
    Index,
    NewProduct,
    SaveProduct,
    )

    


urlpatterns = [
    path('index', Index , name='index'),
    path('new', NewProduct , name='new'),
    path('SaveProduct', SaveProduct , name='SaveProduct'),
    


]
urlpatterns+=[


]

ProductSetup/models.py
from django.db import models
from BasicSettings.models import *

# Create your models here.
class ProductInfo (models.Model):
    ProductName =  models.CharField(max_length=800,blank=False)
    ProductDescripTion = models.CharField(max_length=5000,blank=False)
    ProductSpecification = models.CharField(max_length=8000,blank=False)
    
    ProductCountry = models.ForeignKey(CountryOrigin , on_delete=models.CASCADE)
    ProductCategory = models.ForeignKey(ItemCategory , on_delete=models.CASCADE)
    ProductBrand = models.ForeignKey(ItemBrand , on_delete=models.CASCADE , blank=True)
    ProductColor = models.ManyToManyField(ItemColor,blank=True,null=True)
    
    ProductSize = models.ManyToManyField(ItemSize,blank=True,null=True)
    ProductUOM = models.ForeignKey(UomMaster , on_delete=models.CASCADE)
    ProductCode = models.CharField(max_length=100,blank=False)
    IsActive = models.BooleanField(default=True,blank=False)
    IsDelete = models.BooleanField(default=False,blank=False)
    CreateDate = models.DateTimeField(auto_now_add=True , blank=True)
    CreateBy = models.CharField(max_length=500 , blank=True)
    
    UpdateBy = models.CharField(max_length=500 , blank=True,null=True)
    UpdateDate = models.DateTimeField(auto_now=True,blank=True,null=True)

    DeleteDate = models.DateTimeField( blank=True, null=True)
    DeleteBy = models.CharField(max_length=500 , blank=True,null=True)

    
    

ProductSetup/forms.py
from  django import forms
from .models import *
from BasicSettings.models import CountryOrigin 

from django.forms  import ModelForm  

class ProductForm(ModelForm):
    class Meta:
        model = ProductInfo
        fields = [
            'ProductName',
            'ProductDescripTion',
            
            'ProductCountry',
            'ProductCategory',
            'ProductBrand' ,
            'ProductColor',
            'ProductSize',
            'ProductUOM',
            'IsActive' ]
        labels = {
            'ProductName': "Name",
            'ProductDescripTion': "Description",
            
            'ProductCountry':'Origin',
            'ProductCategory': 'Category',
            'ProductBrand':'Brand',
            'ProductColor':'Color',
            'ProductSize': 'Size',
            'ProductUOM': 'UOM',
            'IsActive': "Active :"
        }
        
        widgets = {
            'ProductName': forms.TextInput(),
            'ProductDescripTion': forms.TextInput(),
            
            # 'ProductColor': forms.ModelMultipleChoiceField( queryset = ItemColor.objects.filter(IsActive=True , IsDelete = False )),
            'IsActive': forms.CheckboxInput(),
        }

    def __init__(self, *args, **kwargs):
        self.postData = None
        self.instance = None
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields['ProductName'].widget.attrs['class']="form-control"
        self.fields['ProductDescripTion'].widget.attrs['class']="form-control"
       
        self.fields['ProductCategory'].widget.attrs['class']="form-control"
        self.fields['ProductCountry'].widget.attrs['class']="form-control"
        self.fields['ProductBrand'].widget.attrs['class']="form-control"
      
        self.fields['ProductColor'].widget.attrs['class']="form-control"
        self.fields['ProductColor'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['ProductColor'].queryset = ItemColor.objects.filter(IsActive=True , IsDelete = False )
        
        self.fields['ProductSize'].widget.attrs['class']="form-control"
        self.fields['ProductSize'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['ProductSize'].queryset = ItemSize.objects.filter(IsActive=True , IsDelete = False )
        
        self.fields['ProductUOM'].widget.attrs['class']="form-control"
        

        self.fields['ProductCategory'].queryset  = ItemCategory.objects.filter(IsActive=True , IsDelete = False )
        self.fields['ProductCategory'].empty_label  =  'Select Category'
        

        self.fields['ProductCountry'].queryset  = CountryOrigin.objects.filter(IsActive=True , IsDelete = False )
        self.fields['ProductCountry'].empty_label  =  'Select Country'

        self.fields['ProductBrand'].queryset  = ItemBrand.objects.filter(IsActive=True , IsDelete = False )
        self.fields['ProductBrand'].empty_label  =  'Select Brand'

        self.fields['ProductColor'].queryset  = ItemColor.objects.filter(IsActive=True , IsDelete = False )
        

        self.fields['ProductSize'].queryset  = ItemSize.objects.filter(IsActive=True , IsDelete = False )
        


    def clean(self):
        data = self.cleaned_data
        name = self.cleaned_data.get("ProductName")
        desc = self.cleaned_data.get("ProductDescripTion")
        category = self.cleaned_data.get("ProductCategory")
        country = self.cleaned_data.get("ProductCountry")
        brand = self.cleaned_data.get("ProductBrand")
        uomMaster = self.cleaned_data.get("ProductUOM")

        if name is None or '':
            raise forms.ValidationError('Product Name Required')
        elif desc is None or '':
            raise forms.ValidationError('Product Description Required')
        elif category is None or '':
            raise forms.ValidationError('Product Category Required')
        elif country is None or '':
            raise forms.ValidationError('Country Origin Required')
        elif brand is None or '':
            raise forms.ValidationError('Brand Required')
        elif uomMaster is None or '':
            raise forms.ValidationError('UOM Required')
        else:
            return data
        

ProductSetup/views.py
from django.shortcuts import render
from .forms import ProductForm
from BasicSettings.models import *
from ProductSetup.models import *
import json
from django.http import JsonResponse , HttpResponse
from ProductSetup.ProductHelper import ProductHelper
from Utility.ResultResponse import ResultResponse
from Utility.AppError import AppError
from django.template.loader import render_to_string

# Create your views here.

_aProductHelper =  ProductHelper()
def Index(request):
    return render(request, 'ProductSetup/index.html', {})



def NewProduct(request):
    masterForm = ProductForm( None)
    context = {
        'masterForm':masterForm,
        
    }
    return render(request, 'ProductSetup/NewProduct.html', context)

def SaveProduct(request):
    aResponse = ResultResponse()
    received_json_data = json.loads(request.body.decode("utf-8"))
    theRequest = request.POST.copy()
    theRequest.__mutable = True
    theRequest.POST=received_json_data
    
    name = received_json_data.get('ProductName')
    description = received_json_data.get('ProductDescripTion')
    country = received_json_data.get('ProductCountry')
    category = received_json_data.get('ProductCategory')
    brand = received_json_data.get('ProductBrand')
    color = received_json_data.get('ProductColor')
    size = received_json_data.get('ProductSize')
    uom = received_json_data.get('ProductUOM')

    masterForm = ProductForm(theRequest.POST)

    if masterForm.is_valid():
        productGenerate = _aProductHelper.GenerateProduct(name ,description,category,country,brand,uom,color,size)
        finalProd = productGenerate[0]
        productColor = productGenerate[1]
        productsize = productGenerate[2]
        # need to add trunsection process
        finalProd.save()

        if productColor is not None:
            finalProd.ProductColor.add(*productColor)
        if productsize is not None:
            finalProd.ProductSize.add(*productsize)
        
        finalProd.ProductCode = _aProductHelper.GenerateProductCode(category = category , productid =finalProd.pk )
        finalProd.save()
        if finalProd.pk>0:
            aResponse.IsSuccess = True
        return JsonResponse(json.dumps(aResponse.__dict__ ), safe=False)
    else:
        appError = AppError()
        template = render_to_string('ProductSetup/_productForm.html' , {'masterForm':masterForm  } )
        appError.TheData = str(template)
        return JsonResponse( json.dumps(appError.__dict__ ) , safe=False)

    # productGenerate = _aProductHelper.GenerateProduct(name ,description,category,country,brand,uom,color,size)
    
    # finalProd = productGenerate[0]
    # productColor = productGenerate[1]
    # productsize = productGenerate[2]

    # need to add trunsection process
    # finalProd.save()

    # if productColor is not None:
    #     finalProd.ProductColor.add(*productColor)
    # if productsize is not None:
    #     finalProd.ProductSize.add(*productsize)
    
    # finalProd.ProductCode = _aProductHelper.GenerateProductCode(category = category , productid =finalProd.pk )
    # finalProd.save()
    # if finalProd.pk>0 :
    #     aResponse.IsSuccess = True
    #     return JsonResponse(json.dumps(aResponse.__dict__ ), safe=False)
    # else:
    #     appError = AppError()

    #     template = render_to_string('ProductSetup/NewProduct.html' , {'masterForm':masterForm  } )
    #     appError.TheData = str(template)
    #     return JsonResponse( json.dumps(appError.__dict__ ) , safe=False)

    

    


    

templates/ProductSetup/NewProduct.html
{% extends "baseTemplates/_baseTemplate.html" %}
{% block content%}


<div class="row"> 
        <div class="col-md-offset-2 col-md-6">
            <div class="box box-primary" >
                
               <form>{% csrf_token %}
                 <div id="fromMaster" >
                    {% include 'ProductSetup/_productForm.html' %}
                </div>
                
               </form>
                <button class="btn btn-success btn-sm" onclick="SaveProduct()" ><span class="fa fa-save"><span>&nbsp; Save </button>
                    
                
                
                  
            </div>
        </div>
</div>
{% load static %}
<script src="{% static 'app_scripts/product.js'%}"></script>
<script type="text/javascript">

const masterForm =$('#fromMaster').html(); 
function SaveProduct(){

    debugger;
    var color = Array();
    var size = Array();
    $("input:checkbox[name=ProductColor]:checked").each(function(){
        color.push(parseInt($(this).val()));
    });
     $("input:checkbox[name=ProductSize]:checked").each(function(){
        size.push(parseInt($(this).val()));
    });
    

    var jsonData = {};

    jsonData["ProductCategory"]  = $.trim($('#id_ProductCategory').val());
    jsonData["ProductName"]  = $.trim($('#id_ProductName').val());
    jsonData["ProductDescripTion"]  = $.trim($('#id_ProductDescripTion').val());
    jsonData["ProductCountry"]  = $.trim($('#id_ProductCountry').val());
    jsonData["ProductBrand"]  = $.trim($('#id_ProductBrand').val());
    jsonData["ProductUOM"]  = $.trim($('#id_ProductUOM').val());
    jsonData["ProductColor"]  = color;
    jsonData["ProductSize"]  = size;
    jsonData["IsActive"] = $('#id_IsActive').is(':checked')?'True':'False';
     AjaxSetup();
     var urlpath = '{% url "SaveProduct"   %}';
        $.ajax({
               
                data:  JSON.stringify(jsonData),
                dataType: 'json',
                url: urlpath,
                type: "POST",

                success:function (response,status, xhr) 
                {
                    debugger;
                      
                    var ct = xhr.getResponseHeader("content-type");

                    
                    if(ct=="application/json")
                    {
                    var error =  JSON.parse(response)
                    var asd = error.HasError
                    
                    if(error.HasError)
                    {
                        swal("Failed", "Operation Failed", "error");
                        $('#fromMaster').empty();
                        $('#fromMaster').append(error.TheData)
                    }
                    if(error["IsSuccess"]==true){
                        swal("Success", "Product Added", "success");
                         $('#fromMaster').empty();
                         $('#fromMaster').html(masterForm);
                          
                      //window.location.href  = '{% url "brands"   %}';
                    }
                }

                }
                
            });

    

}
      function AjaxSetup(){
          $.ajaxSetup({ 
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     } 
    });
}
</script>

{% endblock %}

templates/ProductSetup/_productForm.html
 <div class="row" id="divForProductCategory">
    <label>Category:</label>
    {{masterForm.ProductCategory}}
    <label class="text-danger" >{{masterForm.errors.ProductCategory.as_text }}</label>
      
</div>
 <div class="row" id="divForItemGroup">
    <label>Name:</label>
    {{masterForm.ProductName}}
    <label class="text-danger" >{{masterForm.errors.ProductName.as_text }}</label>
      
</div>
<div class="row" id="divForItemCategory">
    <label>Description:</label>
    {{masterForm.ProductDescripTion}}
    <label class="text-danger" >{{masterForm.errors.ProductDescripTion.as_text }}</label>
      
</div>





<div class="row" id="divForProductCountry">
    <label>Origin:</label>
    {{masterForm.ProductCountry}}
    <label class="text-danger" >{{masterForm.errors.ProductCountry.as_text }}</label>
      
</div>



<div class="row" id="divForProductBrand">
    <label>Brand:</label>
    {{masterForm.ProductBrand}}
    <label class="text-danger" >{{masterForm.errors.ProductBrand.as_text }}</label>
      
</div>

<div class="row" id="divForProductColor">
    <label>Color:</label>
    {{masterForm.ProductColor}}
    <label class="text-danger" >{{masterForm.errors.ProductColor.as_text }}</label>
      
</div>

<div class="row" id="divForProductSize">
    <label>Size:</label>
    {{masterForm.ProductSize}}
    <label class="text-danger" >{{masterForm.errors.ProductSize.as_text }}</label>

</div>

<div class="row" id="divForProductUOM">
    <label>UOM:</label>
    {{masterForm.ProductUOM}}
    <label class="text-danger" >{{masterForm.errors.ProductUOM.as_text }}</label>

</div>


<div class="row" id="divForIsActive">
    <label>Is Active:</label>
    {{masterForm.IsActive}}
    
      
</div>

templates/ProductSetup/index.html
{% extends "baseTemplates/_baseTemplate.html" %}
{% block content%}


<h1>Product Setup Index</h1>
{% endblock %}